Add checks for apt-get update

diff --git a/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb b/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb
--- a/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb
+++ b/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb
@@ -53,6 +53,9 @@ dpkg -s nfs-kernel-server >/dev/null 2>&1
 if [ $? -ne 0 ] ; then
   chmod 1777 /tmp
   apt-get update
+  if [ $? -ne 0 ] ; then
+    log_debug "apt-get update failed"
+  fi
   log_debug "Installing nfs-common"
   apt-get install nfs-common=1:1.2.8-9ubuntu12 -y
   if [ $? -ne 0 ] ; then
