Change NFS mounts
Change NFS mounts to share the tenants and synapse-conigs among all the gateways and pub-store-tm nodes

diff --git a/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb b/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb
--- a/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb
+++ b/pattern-2/bosh-release/jobs/nfs_server/templates/ctl.erb
@@ -19,7 +19,6 @@
 #
 # ----------------------------------------------------------------------------
 
-set +e
 set -xv
 
 script_dir=$(dirname $0)
@@ -32,9 +31,9 @@ pid_file=${run_dir}/pid
 mkdir -p ${run_dir} ${log_dir}
 chown -R vcap:vcap ${run_dir} ${log_dir}
 
-export NFS_EXPORT_SERVER_DIR_APIM=/mnt/nfs-export/wso2am/repository/deployment
-export NFS_EXPORT_SERVER_DIR_GATEWAY=/mnt/nfs-export/gateway/repository/deployment
+export NFS_EXPORT_SYNAPSECONFIGS_DIR_GATEWAY=/mnt/nfs-export/gateway/repository/deployment/server
 export NFS_EXPORT_TENANTS_DIR_GATEWAY=/mnt/nfs-export/gateway/repository/tenants
+export NFS_EXPORT_EXECUTIONPLANS_DIR_APIM=/mnt/nfs-export/wso2am/repository/deployment/server
 
 export DEBUG_LOG=${log_dir}/nfs_server.log
 
@@ -52,25 +51,39 @@ log_debug "Kicking off ctl script as `whoami` with $1"
 
 dpkg -s nfs-kernel-server >/dev/null 2>&1
 if [ $? -ne 0 ] ; then
+  chmod 1777 /tmp
   apt-get update
-  apt-get install nfs-kernel-server -y
+  log_debug "Installing nfs-common"
+  apt-get install nfs-common=1:1.2.8-9ubuntu12 -y
+  if [ $? -ne 0 ] ; then
+    log_debug "Installing nfs-common failed"
+  fi
+
+  log_debug "Installing nfs-kernel-server"
+  apt-get install nfs-kernel-server=1:1.2.8-9ubuntu12 -y
+  if [ $? -ne 0 ] ; then
+    log_debug "Installing nfs-kernel-server failed"
+  fi
 fi
 
 # create the share directory and set permission
 
-mkdir -p ${NFS_EXPORT_SERVER_DIR_APIM}
-mkdir -p ${NFS_EXPORT_SERVER_DIR_GATEWAY}
+mkdir -p ${NFS_EXPORT_SYNAPSECONFIGS_DIR_GATEWAY}
 mkdir -p ${NFS_EXPORT_TENANTS_DIR_GATEWAY}
+mkdir -p ${NFS_EXPORT_EXECUTIONPLANS_DIR_APIM}
 
-chown nobody:nogroup ${NFS_EXPORT_SERVER_DIR_APIM}
-chown nobody:nogroup ${NFS_EXPORT_SERVER_DIR_GATEWAY}
+chown nobody:nogroup ${NFS_EXPORT_SYNAPSECONFIGS_DIR_GATEWAY}
 chown nobody:nogroup ${NFS_EXPORT_TENANTS_DIR_GATEWAY}
+chown nobody:nogroup ${NFS_EXPORT_EXECUTIONPLANS_DIR_APIM}
 
 # configure the exports
 
 if [ -z "$(cat /etc/exports | grep wso2am )" ]; then
-  echo "${NFS_EXPORT_SERVER_DIR_APIM}    *(rw,sync,no_subtree_check)" >> /etc/exports
-  echo "${NFS_EXPORT_SERVER_DIR_GATEWAY}    *(rw,sync,no_subtree_check)" >> /etc/exports
+  echo "${NFS_EXPORT_EXECUTIONPLANS_DIR_APIM}    *(rw,sync,no_subtree_check)" >> /etc/exports
+fi
+
+if [ -z "$(cat /etc/exports | grep gateway )" ]; then
+  echo "${NFS_EXPORT_SYNAPSECONFIGS_DIR_GATEWAY}    *(rw,sync,no_subtree_check)" >> /etc/exports
   echo "${NFS_EXPORT_TENANTS_DIR_GATEWAY}   *(rw,sync,no_subtree_check)" >> /etc/exports
 fi
 
