Change NFS mounts
Change NFS mounts to share the tenants and synapse-conigs among all the gateways and pub-store-tm nodes

diff --git a/pattern-2/bosh-release/jobs/wso2apim/templates/ctl.erb b/pattern-2/bosh-release/jobs/wso2apim/templates/ctl.erb
--- a/pattern-2/bosh-release/jobs/wso2apim/templates/ctl.erb
+++ b/pattern-2/bosh-release/jobs/wso2apim/templates/ctl.erb
@@ -19,7 +19,6 @@
 #
 # ----------------------------------------------------------------------------
 
-set +e
 set -xv
 
 script_dir=$(dirname $0)
@@ -51,9 +50,8 @@ export JAVA_OPTS=" -Xmx${MAX_HEAP}m -Xms${MIN_HEAP}m -XX:MaxPermSize=${MAX_PERMG
 
 export DEBUG_LOG=${log_dir}/wso2apim.log
 
-export NFS_EXPORT_SERVER_DIR=/mnt/nfs-export/wso2am/repository/deployment
-
-export NFS_SHARE_SERVER_DIR=/mnt/nfs-share/wso2am/repository/deployment
+export NFS_EXPORT_EXECUTIONPLANS_DIR=/mnt/nfs-export/wso2am/repository/deployment/server
+export NFS_SHARE_EXECUTIONPLANS_DIR=/mnt/nfs-share/wso2am/repository/deployment/server
 
 touch $DEBUG_LOG
 chmod -R 755 /var/vcap/sys
@@ -67,12 +65,17 @@ log_debug "Kicking off ctl script as `whoami` with $1"
 
 dpkg -s nfs-common >/dev/null 2>&1
 if [ $? -ne 0 ] ; then
+  chmod 1777 /tmp
+  apt-get update
   log_debug "Installing NFS Client"
-  sudo apt-get update
-  sudo apt-get install nfs-common -y
+  apt-get install nfs-common=1:1.2.8-9ubuntu12 -y
+  if [ $? -ne 0 ] ; then
+    log_debug "Installing nfs-common failed"
+  fi
 fi
 
-mkdir -p ${NFS_SHARE_SERVER_DIR}
+mkdir -p ${NFS_SHARE_EXECUTIONPLANS_DIR}
+log_debug "`ls -la ${NFS_SHARE_EXECUTIONPLANS_DIR}`"
 
 case $1 in
 
@@ -105,15 +108,15 @@ case $1 in
     cp /var/vcap/packages/jdbcdrivers/* ${WSO2_APIM_HOME}/repository/components/lib/
 
     mkdir /tmp/wso2am
-    mv $WSO2_APIM_HOME/repository/deployment/server/ /tmp/wso2am/
+    mv $WSO2_APIM_HOME/repository/deployment/server/executionplans/ /tmp/wso2am/
 
-    mount -t nfs <%= link("nfs-server").instances[0].address %>:${NFS_EXPORT_SERVER_DIR} ${NFS_SHARE_SERVER_DIR}
+    mount -t nfs <%= link("nfs-server").instances[0].address %>:${NFS_EXPORT_EXECUTIONPLANS_DIR} ${NFS_SHARE_EXECUTIONPLANS_DIR}
 
-    if [ -z "$(ls -A ${NFS_SHARE_SERVER_DIR})" ]; then
-      cp -r /tmp/wso2am/* ${NFS_SHARE_SERVER_DIR}/
+    if [ -z "$(ls -A ${NFS_SHARE_EXECUTIONPLANS_DIR})" ]; then
+      cp -r /tmp/wso2am/* ${NFS_SHARE_EXECUTIONPLANS_DIR}/
     fi
 
-    ln -s ${NFS_SHARE_SERVER_DIR}/server $WSO2_APIM_HOME/repository/deployment
+    ln -s ${NFS_SHARE_EXECUTIONPLANS_DIR}/executionplans $WSO2_APIM_HOME/repository/deployment/server
 
     # Create symbolic link for logging
     ln -s $WSO2_APIM_HOME/repository/logs/ ${log_dir}
@@ -140,7 +143,7 @@ case $1 in
     kill -9 `cat ${pid_file}`
     rm -f ${pid_file}
     sleep 10
-    umount ${NFS_SHARE_SERVER_DIR}
+    umount ${NFS_SHARE_EXECUTIONPLANS_DIR}
 
     ;;
 
